"""
fitness_planner.py — Module 1: Firefighter Fitness Planner

Generates a personalized weekly physical readiness plan based on the
firefighter's role, fitness level, available equipment, and goals.
"""

import streamlit as st
from modules.llm_client import is_api_available, run_with_spinner, show_no_api_key_warning, module_header, output_header

# ---------------------------------------------------------------------------
# Sample output shown when no API key is configured
# ---------------------------------------------------------------------------
SAMPLE_OUTPUT = """
## Weekly Firefighter Fitness Plan
**Profile:** Intermediate | Age 34 | Goal: Work Capacity | 4 days/week | Equipment: Dumbbells, Pull-up bar, Bodyweight

---

### Overview
This plan prioritizes functional work capacity — the ability to sustain high-intensity physical effort while wearing SCBA and PPE. Expect a mix of strength circuits, cardiovascular conditioning, and mobility work modeled on the physical demands of fireground operations.

---

### Weekly Schedule

| Day | Focus | Duration |
|-----|-------|----------|
| Monday | Strength + Functional Power | 50 min |
| Tuesday | Cardio Endurance (Zone 2) | 40 min |
| Wednesday | Rest or Active Recovery | — |
| Thursday | HIRT Circuit (Fireground Sim) | 45 min |
| Friday | Strength + Grip / Upper Body | 50 min |
| Saturday | Long Aerobic (Run/Ruck) | 45–60 min |
| Sunday | Rest | — |

---

### Day-by-Day Breakdown

**Monday — Strength & Functional Power**
- Warm-up: 5 min jump rope / dynamic stretching
- 4 rounds: Dumbbell deadlift x 10, Pull-ups x 6, DB push press x 10, Rest 90 sec
- Core: Plank 3x45 sec, Dead bug 3x10/side
- Cool-down: 5 min hip flexor / hamstring stretch

**Tuesday — Cardio Endurance (Zone 2)**
- 35–40 min steady-state run or row at conversational pace (130–150 BPM)
- Goal: aerobic base, recovery capacity, cardiovascular efficiency

**Thursday — HIRT Circuit (Fireground Simulation)**
- 5 rounds for time: Farmer carry (DBs, 50 ft), Pull-ups x 5, DB thruster x 8, Stair climb x 2 flights (or step-ups x 20), 90 sec rest
- Simulates sustained high-intensity work with upper-body loading

**Friday — Strength & Grip / Upper**
- 4 rounds: DB bent-over row x 10, Diamond push-ups x 12, Dead hang 30 sec, DB curl to press x 10
- Finisher: 3x max pull-ups

**Saturday — Long Aerobic**
- 45–60 min outdoor run or weighted ruck (20–30 lbs)
- Rucking recommended — closely mimics SCBA/gear loads on the fireground

---

### Progression Recommendations
- **Weeks 1–2:** Establish baseline — focus on form over load
- **Weeks 3–4:** Increase dumbbell weight by 5 lbs on compound movements
- **Weeks 5–6:** Add one additional circuit round to Thursday session
- **Monthly:** Re-evaluate max pull-ups and 1.5-mile run time as benchmark metrics

---

### Recovery & Mobility Notes
- Prioritize 7–8 hours sleep — fireground readiness degrades significantly with sleep debt
- Post-shift stretching: focus on hip flexors, thoracic spine, and shoulders (areas stressed by PPE)
- Hydration: 0.5–1 oz per lb of bodyweight daily; increase on drill days
- Consider foam rolling thoracic spine and IT band 2–3x per week

---
*Plan generated by FireReady AI. Consult your physician before beginning any new exercise program.*
"""


def build_prompt(inputs: dict) -> str:
    """Construct the LLM prompt from user inputs."""
    equipment_str = ", ".join(inputs["equipment"]) if inputs["equipment"] else "bodyweight only"
    limitations_str = inputs["limitations"] if inputs["limitations"].strip() else "None noted"

    return f"""Create a detailed, practical weekly firefighter fitness plan for the following profile:

- **Role:** {inputs['role']}
- **Age:** {inputs['age']}
- **Fitness Level:** {inputs['fitness_level']}
- **Primary Goal:** {inputs['goal']}
- **Training Days Per Week:** {inputs['days_per_week']}
- **Available Equipment:** {equipment_str}
- **Notes / Limitations:** {limitations_str}

Structure your response with these sections:

## Weekly Firefighter Fitness Plan
Start with a brief profile summary and overview paragraph explaining the training philosophy for this person's goal and role.

### Weekly Schedule
Provide a table showing each training day, focus area, and approximate duration.

### Day-by-Day Breakdown
For each training day, list:
- Warm-up
- Main workout with sets/reps/rest
- Cool-down or finisher

### Progression Recommendations
Provide a 6-week progression plan with specific benchmarks.

### Recovery & Mobility Notes
Include recovery recommendations relevant to fire service work schedules (shift work, drill nights, etc.).

Keep it practical and specific. Avoid filler. This should sound like advice from a fire department fitness coordinator, not a generic personal trainer."""


def render() -> None:
    """Render the Fitness Planner module."""
    module_header(
        icon="💪",
        title="Fitness Planner",
        description=(
            "Build a personalized weekly physical readiness plan tailored to your role, fitness level, "
            "available equipment, and primary goal. Every plan is built around the functional demands "
            "of fire service work — not generic gym programming."
        ),
        audience="All Firefighters · All Ranks · Recruits",
    )
    st.divider()

    # ---- Input Form --------------------------------------------------------
    with st.form("fitness_form"):
        col1, col2 = st.columns(2)

        with col1:
            role = st.selectbox(
                "Role / Position",
                ["Firefighter", "Driver / Engineer", "Company Officer", "Training Officer", "Recruit / Probationary"],
            )
            age = st.number_input("Age", min_value=18, max_value=65, value=30, step=1)
            fitness_level = st.selectbox(
                "Current Fitness Level",
                ["Beginner — limited recent training",
                 "Intermediate — training 2–3x/week",
                 "Advanced — training 4+ days/week consistently"],
            )
            goal = st.selectbox(
                "Primary Training Goal",
                ["Work Capacity (fireground performance)",
                 "Cardiovascular Endurance",
                 "Strength & Power",
                 "Mobility & Flexibility",
                 "Recovery & Maintenance"],
            )

        with col2:
            days_per_week = st.slider("Training Days Per Week", min_value=3, max_value=6, value=4)
            equipment = st.multiselect(
                "Available Equipment (select all that apply)",
                ["Bodyweight only", "Dumbbells", "Barbell & Rack", "Pull-up Bar",
                 "Kettlebells", "Full Gym Access", "Station Equipment (hose, ladders, SCBA)"],
                default=["Dumbbells", "Pull-up Bar"],
            )
            limitations = st.text_area(
                "Notes, Injuries, or Limitations (optional)",
                placeholder="e.g., recovering from shoulder surgery, no running due to knee, shift work schedule...",
                height=120,
            )

        submitted = st.form_submit_button("Generate Fitness Plan", use_container_width=True)

    # ---- Output ------------------------------------------------------------
    if submitted:
        if not is_api_available():
            show_no_api_key_warning()
            result = SAMPLE_OUTPUT
        else:
            inputs = {
                "role": role,
                "age": age,
                "fitness_level": fitness_level.split(" —")[0],
                "goal": goal,
                "days_per_week": days_per_week,
                "equipment": equipment if equipment else ["bodyweight only"],
                "limitations": limitations,
            }
            result = run_with_spinner(build_prompt(inputs), max_tokens=2500)
            if result is None:
                st.error("Could not generate plan. Check your API key and try again.")
                return

        # Display output
        st.divider()
        output_header("Your Personalized Training Plan")
        with st.container(border=True):
            st.markdown(result)

        st.download_button(
            label="⬇  Download Plan as Markdown",
            data=result,
            file_name="fireready_fitness_plan.md",
            mime="text/markdown",
        )
